name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir coopclient/.config
      - run: echo "${{ secrets.COOP_MOBILE_USERNAME }}" > coopclient/.config/username
      - run: echo "${{ secrets.COOP_MOBILE_PASSWORD }}" > coopclient/.config/password
      - name: Test
        run: "./gradlew test"
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: app/build
  release:
    name: Release
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Load Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > app/keystore.jks
        echo "${{ secrets.KEYSTORE_PROPS }}" > app/keystore.properties
    - name: Build
      run: "./gradlew bundleRelease && chmod a+r app/build/outputs/bundle/release/app-release.aab"
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload GitHub Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/bundle/release/app-release.aab
        asset_name: app-release.aab
        asset_content_type: application/zip
  googleplay:
    name: Google Play
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
    - name: Create Play Store Release
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        packageName: de.lorenzgorse.coopmobile
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: beta
