name: CI
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"
      - run: mkdir coopclient/.config
      - run: echo "${{ secrets.COOP_MOBILE_USERNAME }}" > coopclient/.config/username
      - run: echo "${{ secrets.COOP_MOBILE_PASSWORD }}" > coopclient/.config/password
      - name: Test
        run: "./gradlew test"
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: app/build
  release:
    name: Release
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: "oracle"
        java-version: "17"
    - name: Load Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > app/keystore.jks
        echo "${{ secrets.KEYSTORE_PROPS }}" > app/keystore.properties
    - name: Load Bifrost client key
      run: echo "coop_mobile_client_key=${{ secrets.BIFROST_CLIENT_KEY }}" > app/src/main/assets/bifrost.properties
    - name: Build
      run: "./gradlew bundleRelease && chmod a+r app/build/outputs/bundle/release/app-release.aab"
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        files: app/build/outputs/bundle/release/app-release.aab
    - name: Create Play Store Release
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        packageName: de.lorenzgorse.coopmobile
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
