name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir coopclient/.config
    - run: echo "${{ secrets.COOP_MOBILE_USERNAME }}" > coopclient/.config/username
    - run: echo "${{ secrets.COOP_MOBILE_PASSWORD }}" > coopclient/.config/password
    - name: Test
      run: "./gradlew test"
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: app/build
