name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew test"
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
